#!/bin/bash
# SQANTI3 Stage 1b — Reference QC
# Runs the reference GTF through SQANTI3 QC to produce ref_classification.txt,
# which is required as input by Stage 3 (Rescue). Runs in parallel with Stage 1a.
#
# Args:
#   $1  Path to stage refqc config YAML (generated by orchestrator)
#   $2  Path to SQANTI3 SIF

set -euo pipefail

module load apptainer

STAGE_CONFIG="${1:?ERROR: Stage config not provided}"
SIF="${2:?ERROR: SIF path not provided}"

PROJECT_ROOT=/groups/tprice/pipelines
SCRATCH_ROOT=/scratch/juno/$USER
WORK_ROOT=/work/$USER

if [[ ! -f "$STAGE_CONFIG" ]]; then
    echo "ERROR: Stage config not found: $STAGE_CONFIG"
    exit 1
fi

if [[ ! -f "$SIF" ]]; then
    echo "ERROR: SQANTI3 SIF not found: $SIF"
    exit 1
fi

echo "====================================================================="
echo "  SQANTI3 Stage 1b — Reference QC"
echo "  Config: $STAGE_CONFIG"
echo "====================================================================="

apptainer exec \
    --env HOME=/tmp \
    --env PYTHONNOUSERSITE=1 \
    --bind "${PROJECT_ROOT}:${PROJECT_ROOT}" \
    --bind "${SCRATCH_ROOT}:${SCRATCH_ROOT}" \
    --bind "${WORK_ROOT}:${WORK_ROOT}" \
    "$SIF" \
    conda run --no-capture-output -n sqanti3 \
    sqanti3 qc -c "$STAGE_CONFIG"

# Rename classification output to canonical name expected by rescue
OUTDIR=$(grep -E "^  dir:" "$STAGE_CONFIG" | head -1 | sed "s/.*dir:[[:space:]]*'//; s/'[[:space:]]*$//")
if [[ -n "$OUTDIR" ]]; then
    # Find the classification file (named ref_classification.txt or similar)
    CLASSIF=$(find "$OUTDIR" -name "*_classification.txt" | head -1)
    if [[ -n "$CLASSIF" && "$(basename "$CLASSIF")" != "ref_classification.txt" ]]; then
        cp "$CLASSIF" "$OUTDIR/ref_classification.txt"
        echo "Copied: $(basename "$CLASSIF") -> ref_classification.txt"
    fi
fi

echo "Stage 1b complete."
