#!/bin/bash
# SQANTI3 Stage 3 — Rescue
# Rescues filtered-out isoforms using reference QC classifications.
# Depends on Stage 2 (Filter) AND Stage 1b (Reference QC) completing successfully.
# Also performs final stage-out: rsync outputs to run directory.
#
# Args:
#   $1  Path to stage rescue config YAML (generated by orchestrator)
#   $2  Path to SQANTI3 SIF
#   $3  SQANTI3 output root (e.g. /work/$USER/sqanti3/sample)
#   $4  Run directory (for stage-out archiving)

set -euo pipefail

module load apptainer

STAGE_CONFIG="${1:?ERROR: Stage config not provided}"
SIF="${2:?ERROR: SIF path not provided}"
OUTDIR="${3:?ERROR: Output dir not provided}"
RUN_DIR="${4:?ERROR: Run dir not provided}"

PROJECT_ROOT=/groups/tprice/pipelines
SCRATCH_ROOT=/scratch/juno/$USER
WORK_ROOT=/work/$USER

if [[ ! -f "$STAGE_CONFIG" ]]; then
    echo "ERROR: Stage config not found: $STAGE_CONFIG"
    exit 1
fi

if [[ ! -f "$SIF" ]]; then
    echo "ERROR: SQANTI3 SIF not found: $SIF"
    exit 1
fi

echo "====================================================================="
echo "  SQANTI3 Stage 3 — Rescue"
echo "  Config: $STAGE_CONFIG"
echo "====================================================================="

apptainer exec \
    --env HOME=/tmp \
    --env PYTHONNOUSERSITE=1 \
    --bind "${PROJECT_ROOT}:${PROJECT_ROOT}" \
    --bind "${SCRATCH_ROOT}:${SCRATCH_ROOT}" \
    --bind "${WORK_ROOT}:${WORK_ROOT}" \
    "$SIF" \
    conda run --no-capture-output -n sqanti3 \
    sqanti3 rescue -c "$STAGE_CONFIG"

echo "Stage 3 complete."

# ── Stage-out: archive all outputs to run directory ──────────────────────────

if [[ -n "$RUN_DIR" && -d "$OUTDIR" ]]; then
    echo ""
    echo "[HYPERION] Data Relays Synchronizing — Archiving results to run directory"

    mkdir -p "$RUN_DIR/outputs"
    rsync -a --checksum "$OUTDIR/" "$RUN_DIR/outputs/"

    OUTPUT_DIFF=$(rsync -a --checksum --dry-run "$OUTDIR/" "$RUN_DIR/outputs/" 2>&1)
    if [[ -z "$OUTPUT_DIFF" ]]; then
        echo "[HYPERION] Data Relays Synchronized — Archive verification PASSED"
    else
        echo "[HYPERION] WARNING: Archive verification detected differences."
        echo "$OUTPUT_DIFF"
    fi

    echo ""
    echo "Final outputs archived to: $RUN_DIR/outputs/"
    echo ""
    echo "Key output files:"
    echo "  QC classification:  $RUN_DIR/outputs/qc/*_classification.txt"
    echo "  Filtered GTF:       $RUN_DIR/outputs/filter/*.filtered.gtf"
    echo "  Rescued GTF:        $RUN_DIR/outputs/rescue/*_rescued.gtf"
fi
