#!/bin/bash
# SQANTI3 Stage 2 — Filter
# Filters QC output using rules-based or ML approach.
# Depends on Stage 1a (long-read QC) completing successfully.
#
# Args:
#   $1  Path to stage filter config YAML (generated by orchestrator)
#   $2  Path to SQANTI3 SIF

set -euo pipefail

module load apptainer

STAGE_CONFIG="${1:?ERROR: Stage config not provided}"
SIF="${2:?ERROR: SIF path not provided}"

PROJECT_ROOT=/groups/tprice/pipelines
SCRATCH_ROOT=/scratch/juno/$USER
WORK_ROOT=/work/$USER

if [[ ! -f "$STAGE_CONFIG" ]]; then
    echo "ERROR: Stage config not found: $STAGE_CONFIG"
    exit 1
fi

if [[ ! -f "$SIF" ]]; then
    echo "ERROR: SQANTI3 SIF not found: $SIF"
    exit 1
fi

echo "====================================================================="
echo "  SQANTI3 Stage 2 — Filter"
echo "  Config: $STAGE_CONFIG"
echo "====================================================================="

apptainer exec \
    --writable-tmpfs \
    --env HOME=/tmp \
    --env PYTHONNOUSERSITE=1 \
    --bind "${PROJECT_ROOT}:${PROJECT_ROOT}" \
    --bind "${SCRATCH_ROOT}:${SCRATCH_ROOT}" \
    --bind "${WORK_ROOT}:${WORK_ROOT}" \
    "$SIF" \
    conda run --no-capture-output -n sqanti3 \
    sqanti3 filter -c "$STAGE_CONFIG"

echo "Stage 2 complete."
