#!/bin/bash
# SQANTI3 Stage 1a — Long-read QC
# Submitted by sqanti3_slurm_template.sh (orchestrator) with dynamic --cpus and --mem.
# Do NOT submit this script directly; use tjp-launch sqanti3.
#
# Args:
#   $1  Path to stage QC config YAML (generated by orchestrator)
#   $2  Path to SQANTI3 SIF

set -euo pipefail

module load apptainer

STAGE_CONFIG="${1:?ERROR: Stage config not provided}"
SIF="${2:?ERROR: SIF path not provided}"

PROJECT_ROOT=/groups/tprice/pipelines
SCRATCH_ROOT=/scratch/juno/$USER
WORK_ROOT=/work/$USER

if [[ ! -f "$STAGE_CONFIG" ]]; then
    echo "ERROR: Stage config not found: $STAGE_CONFIG"
    exit 1
fi

if [[ ! -f "$SIF" ]]; then
    echo "ERROR: SQANTI3 SIF not found: $SIF"
    exit 1
fi

echo "====================================================================="
echo "  SQANTI3 Stage 1a — Long-read QC"
echo "  Config: $STAGE_CONFIG"
echo "====================================================================="

apptainer exec \
    --env HOME=/tmp \
    --env PYTHONNOUSERSITE=1 \
    --bind "${PROJECT_ROOT}:${PROJECT_ROOT}" \
    --bind "${SCRATCH_ROOT}:${SCRATCH_ROOT}" \
    --bind "${WORK_ROOT}:${WORK_ROOT}" \
    "$SIF" \
    conda run --no-capture-output -n sqanti3 \
    sqanti3 qc -c "$STAGE_CONFIG"

echo "Stage 1a complete."
